# Generated by Django 5.2.3 on 2025-07-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Manual Testing', 'Manual Testing'), ('Automation Testing', 'Automation Testing'), ('API Testing', 'API Testing'), ('Mobile Testing', 'Mobile Testing'), ('Python Development', 'Python Development'), ('java Development', 'java Development'), ('UI/UX', 'UI/UX'), ('mern Stack', 'mern Stack')], max_length=50)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advance', 'Advance')], max_length=50)),
                ('price_type', models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('students', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('instructor', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/images/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='courses/videos/')),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('use_youtube_thumbnail', models.BooleanField(default=False)),
                ('description', models.TextField()),
            ],
        ),
    ]
