# Generated by Django 5.1.6 on 2025-07-23 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_alter_userprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='courses',
            field=models.ManyToManyField(blank=True, to='lms.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.CharField(choices=[('Pramod', 'Pramod'), ('Mani', 'Mani'), ('Bharat', 'Bharat'), ('Kartik', 'Bob Brown')], max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.organizationprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('organization', 'Organization'), ('admin', 'Admin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
