# Generated by Django 5.1.6 on 2025-07-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_batch_courses_alter_course_instructor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='courses',
            field=models.ManyToManyField(related_name='batches', to='lms.course'),
        ),
    ]
